name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux x64
        run: |
          cd goscan
          GOOS=linux GOARCH=amd64 go build -o goscan-linux-amd64

      - name: Build macOS ARM64
        run: |
          cd goscan
          GOOS=darwin GOARCH=arm64 go build -o goscan-darwin-arm64

      - name: Build Windows x64
        run: |
          cd goscan
          GOOS=windows GOARCH=amd64 go build -o goscan-windows-amd64.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            goscan/goscan-linux-amd64
            goscan/goscan-darwin-arm64
            goscan/goscan-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
